export type StockLevel = 'critical' | 'low' | 'normal' | 'full';
export type ItemCategory = 'liquor' | 'food' | 'beverage' | 'snacks';
export type OrderStatus = 'pending' | 'approved' | 'in-transit' | 'delivered';

export interface InventoryItem {
  id: string;
  name: string;
  category: ItemCategory;
  currentStock: number;
  maxCapacity: number;
  reorderThreshold: number;
  criticalThreshold: number;
  unit: string;
  consumptionRate: number; // units per hour during peak
  lastRestocked: Date;
}

export interface Lounge {
  id: string;
  name: string;
  terminal: string;
  capacity: number;
  currentOccupancy: number;
  inventory: InventoryItem[];
}

export interface RestockOrder {
  id: string;
  loungeId: string;
  loungeName: string;
  items: {
    itemId: string;
    itemName: string;
    quantity: number;
  }[];
  status: OrderStatus;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  createdAt: Date;
  estimatedDelivery?: Date;
  autoGenerated: boolean;
}

export interface PeakFlight {
  id: string;
  flightNumber: string;
  departure: Date;
  terminal: string;
  expectedPassengers: number;
  loungeAccess: boolean;
}

export interface Alert {
  id: string;
  loungeId: string;
  loungeName: string;
  itemName: string;
  currentStock: number;
  threshold: number;
  severity: 'critical' | 'warning' | 'info';
  message: string;
  timestamp: Date;
  acknowledged: boolean;
}
