import { RestockOrder } from '../types/inventory';
import { formatDateTime } from '../utils/inventoryUtils';
import { Package, Clock, CheckCircle, Truck, AlertCircle } from 'lucide-react';
import { Badge } from './ui/badge';
import { Card } from './ui/card';

interface RestockOrderCardProps {
  order: RestockOrder;
}

export function RestockOrderCard({ order }: RestockOrderCardProps) {
  const getStatusIcon = () => {
    switch (order.status) {
      case 'pending':
        return <Clock className="w-4 h-4" />;
      case 'approved':
        return <CheckCircle className="w-4 h-4" />;
      case 'in-transit':
        return <Truck className="w-4 h-4" />;
      case 'delivered':
        return <Package className="w-4 h-4" />;
    }
  };

  const getStatusColor = () => {
    switch (order.status) {
      case 'pending':
        return 'bg-gray-100 text-gray-800 border-gray-300';
      case 'approved':
        return 'bg-blue-100 text-blue-800 border-blue-300';
      case 'in-transit':
        return 'bg-purple-100 text-purple-800 border-purple-300';
      case 'delivered':
        return 'bg-green-100 text-green-800 border-green-300';
    }
  };

  const getPriorityColor = () => {
    switch (order.priority) {
      case 'urgent':
        return 'destructive';
      case 'high':
        return 'outline';
      case 'medium':
        return 'secondary';
      case 'low':
        return 'secondary';
    }
  };

  return (
    <Card className="p-4 hover:shadow-md transition-all">
      <div className="flex items-start justify-between mb-3">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-medium">Order #{order.id.toUpperCase()}</h3>
            {order.autoGenerated && (
              <Badge variant="secondary" className="text-xs">
                Auto
              </Badge>
            )}
          </div>
          <p className="text-sm text-gray-600">{order.loungeName}</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant={getPriorityColor()}>
            {order.priority}
          </Badge>
        </div>
      </div>

      <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm mb-3 border ${getStatusColor()}`}>
        {getStatusIcon()}
        <span className="capitalize">{order.status.replace('-', ' ')}</span>
      </div>

      <div className="space-y-2 mb-3">
        {order.items.map((item) => (
          <div key={item.itemId} className="flex justify-between text-sm">
            <span className="text-gray-700">{item.itemName}</span>
            <span className="font-medium">×{item.quantity}</span>
          </div>
        ))}
      </div>

      <div className="text-xs text-gray-600 space-y-1 pt-3 border-t">
        <div className="flex justify-between">
          <span>Created:</span>
          <span>{formatDateTime(order.createdAt)}</span>
        </div>
        {order.estimatedDelivery && (
          <div className="flex justify-between">
            <span>Est. Delivery:</span>
            <span className="font-medium">{formatDateTime(order.estimatedDelivery)}</span>
          </div>
        )}
      </div>
    </Card>
  );
}
