import { Lounge, RestockOrder, PeakFlight, Alert, InventoryItem } from '../types/inventory';

// Helper to generate dates
const now = new Date('2026-02-27T14:30:00');
const addHours = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000);

// Sample inventory items
const createInventoryItem = (
  id: string,
  name: string,
  category: InventoryItem['category'],
  currentStock: number,
  maxCapacity: number,
  reorderThreshold: number,
  criticalThreshold: number,
  unit: string,
  consumptionRate: number
): InventoryItem => ({
  id,
  name,
  category,
  currentStock,
  maxCapacity,
  reorderThreshold,
  criticalThreshold,
  unit,
  consumptionRate,
  lastRestocked: addHours(-Math.random() * 48),
});

// Lounge inventory templates
const terminalAInventory: InventoryItem[] = [
  createInventoryItem('ta-1', 'Champagne', 'liquor', 12, 48, 20, 10, 'bottles', 3),
  createInventoryItem('ta-2', 'Vodka', 'liquor', 8, 36, 15, 8, 'bottles', 2.5),
  createInventoryItem('ta-3', 'Whiskey', 'liquor', 22, 40, 18, 10, 'bottles', 2),
  createInventoryItem('ta-4', 'Wine (Red)', 'liquor', 15, 50, 20, 10, 'bottles', 3.5),
  createInventoryItem('ta-5', 'Beer', 'beverage', 45, 120, 50, 25, 'bottles', 8),
  createInventoryItem('ta-6', 'Sparkling Water', 'beverage', 38, 100, 40, 20, 'bottles', 6),
  createInventoryItem('ta-7', 'Fresh Sandwiches', 'food', 18, 60, 25, 12, 'units', 5),
  createInventoryItem('ta-8', 'Salad Bowls', 'food', 22, 50, 20, 10, 'units', 4),
  createInventoryItem('ta-9', 'Cheese Platter', 'food', 8, 25, 12, 6, 'units', 2),
  createInventoryItem('ta-10', 'Mixed Nuts', 'snacks', 32, 80, 30, 15, 'bowls', 3),
];

const terminalBInventory: InventoryItem[] = [
  createInventoryItem('tb-1', 'Champagne', 'liquor', 5, 48, 20, 10, 'bottles', 3),
  createInventoryItem('tb-2', 'Vodka', 'liquor', 18, 36, 15, 8, 'bottles', 2.5),
  createInventoryItem('tb-3', 'Gin', 'liquor', 14, 30, 15, 8, 'bottles', 2),
  createInventoryItem('tb-4', 'Wine (White)', 'liquor', 28, 50, 20, 10, 'bottles', 3.5),
  createInventoryItem('tb-5', 'Beer', 'beverage', 62, 120, 50, 25, 'bottles', 8),
  createInventoryItem('tb-6', 'Orange Juice', 'beverage', 25, 60, 25, 12, 'liters', 4),
  createInventoryItem('tb-7', 'Sushi Rolls', 'food', 14, 40, 18, 9, 'trays', 4),
  createInventoryItem('tb-8', 'Hot Meals', 'food', 30, 60, 25, 12, 'portions', 5),
  createInventoryItem('tb-9', 'Fruit Platter', 'food', 20, 35, 15, 8, 'units', 3),
  createInventoryItem('tb-10', 'Crackers', 'snacks', 45, 100, 40, 20, 'boxes', 4),
];

const terminalCInventory: InventoryItem[] = [
  createInventoryItem('tc-1', 'Champagne', 'liquor', 25, 48, 20, 10, 'bottles', 3),
  createInventoryItem('tc-2', 'Rum', 'liquor', 12, 30, 15, 8, 'bottles', 2),
  createInventoryItem('tc-3', 'Whiskey', 'liquor', 8, 40, 18, 10, 'bottles', 2),
  createInventoryItem('tc-4', 'Wine (Rosé)', 'liquor', 32, 45, 20, 10, 'bottles', 3),
  createInventoryItem('tc-5', 'Craft Beer', 'beverage', 28, 80, 35, 18, 'bottles', 6),
  createInventoryItem('tc-6', 'Coffee', 'beverage', 40, 100, 45, 22, 'servings', 10),
  createInventoryItem('tc-7', 'Pastries', 'food', 35, 80, 35, 18, 'units', 6),
  createInventoryItem('tc-8', 'Soup', 'food', 42, 70, 30, 15, 'portions', 5),
  createInventoryItem('tc-9', 'Desserts', 'food', 25, 50, 22, 11, 'units', 4),
  createInventoryItem('tc-10', 'Chips', 'snacks', 55, 120, 50, 25, 'bags', 5),
];

export const mockLounges: Lounge[] = [
  {
    id: 'lounge-a',
    name: 'Premium Lounge A',
    terminal: 'Terminal A',
    capacity: 150,
    currentOccupancy: 95,
    inventory: terminalAInventory,
  },
  {
    id: 'lounge-b',
    name: 'Business Lounge B',
    terminal: 'Terminal B',
    capacity: 200,
    currentOccupancy: 142,
    inventory: terminalBInventory,
  },
  {
    id: 'lounge-c',
    name: 'Executive Lounge C',
    terminal: 'Terminal C',
    capacity: 180,
    currentOccupancy: 88,
    inventory: terminalCInventory,
  },
];

export const mockRestockOrders: RestockOrder[] = [
  {
    id: 'ro-1',
    loungeId: 'lounge-a',
    loungeName: 'Premium Lounge A',
    items: [
      { itemId: 'ta-1', itemName: 'Champagne', quantity: 36 },
      { itemId: 'ta-2', itemName: 'Vodka', quantity: 28 },
    ],
    status: 'in-transit',
    priority: 'urgent',
    createdAt: addHours(-2),
    estimatedDelivery: addHours(1),
    autoGenerated: true,
  },
  {
    id: 'ro-2',
    loungeId: 'lounge-b',
    loungeName: 'Business Lounge B',
    items: [
      { itemId: 'tb-1', itemName: 'Champagne', quantity: 43 },
      { itemId: 'tb-7', itemName: 'Sushi Rolls', quantity: 26 },
    ],
    status: 'approved',
    priority: 'urgent',
    createdAt: addHours(-0.5),
    estimatedDelivery: addHours(2.5),
    autoGenerated: true,
  },
  {
    id: 'ro-3',
    loungeId: 'lounge-c',
    loungeName: 'Executive Lounge C',
    items: [
      { itemId: 'tc-3', itemName: 'Whiskey', quantity: 32 },
    ],
    status: 'pending',
    priority: 'high',
    createdAt: addHours(-0.2),
    autoGenerated: true,
  },
  {
    id: 'ro-4',
    loungeId: 'lounge-a',
    loungeName: 'Premium Lounge A',
    items: [
      { itemId: 'ta-9', itemName: 'Cheese Platter', quantity: 17 },
      { itemId: 'ta-7', itemName: 'Fresh Sandwiches', quantity: 42 },
    ],
    status: 'delivered',
    priority: 'medium',
    createdAt: addHours(-12),
    estimatedDelivery: addHours(-6),
    autoGenerated: true,
  },
];

export const mockPeakFlights: PeakFlight[] = [
  {
    id: 'pf-1',
    flightNumber: 'AA 1234',
    departure: addHours(1.5),
    terminal: 'Terminal A',
    expectedPassengers: 280,
    loungeAccess: true,
  },
  {
    id: 'pf-2',
    flightNumber: 'UA 5678',
    departure: addHours(2),
    terminal: 'Terminal B',
    expectedPassengers: 320,
    loungeAccess: true,
  },
  {
    id: 'pf-3',
    flightNumber: 'DL 9012',
    departure: addHours(2.5),
    terminal: 'Terminal A',
    expectedPassengers: 250,
    loungeAccess: true,
  },
  {
    id: 'pf-4',
    flightNumber: 'BA 3456',
    departure: addHours(3),
    terminal: 'Terminal C',
    expectedPassengers: 380,
    loungeAccess: true,
  },
  {
    id: 'pf-5',
    flightNumber: 'LH 7890',
    departure: addHours(4),
    terminal: 'Terminal B',
    expectedPassengers: 300,
    loungeAccess: true,
  },
];

export const generateAlerts = (lounges: Lounge[]): Alert[] => {
  const alerts: Alert[] = [];
  
  lounges.forEach((lounge) => {
    lounge.inventory.forEach((item) => {
      const percentage = (item.currentStock / item.maxCapacity) * 100;
      
      if (item.currentStock <= item.criticalThreshold) {
        alerts.push({
          id: `alert-${lounge.id}-${item.id}`,
          loungeId: lounge.id,
          loungeName: lounge.name,
          itemName: item.name,
          currentStock: item.currentStock,
          threshold: item.criticalThreshold,
          severity: 'critical',
          message: `CRITICAL: ${item.name} at ${item.currentStock} ${item.unit} (${percentage.toFixed(0)}%)`,
          timestamp: addHours(-Math.random() * 1),
          acknowledged: false,
        });
      } else if (item.currentStock <= item.reorderThreshold) {
        alerts.push({
          id: `alert-${lounge.id}-${item.id}`,
          loungeId: lounge.id,
          loungeName: lounge.name,
          itemName: item.name,
          currentStock: item.currentStock,
          threshold: item.reorderThreshold,
          severity: 'warning',
          message: `Low stock: ${item.name} at ${item.currentStock} ${item.unit} (${percentage.toFixed(0)}%)`,
          timestamp: addHours(-Math.random() * 2),
          acknowledged: false,
        });
      }
    });
  });
  
  return alerts.sort((a, b) => {
    const severityOrder = { critical: 0, warning: 1, info: 2 };
    return severityOrder[a.severity] - severityOrder[b.severity];
  });
};
